### ISSUE TITLE
just a question about SSL

### ISSUE THREAD

**Issue by quocbao1087** [overint/php-paypal-ipn#1]
Hi,
This is just a question for my limited knowledge.

I want to know if 
`$this->use_local_certs = false;`
I mean what happens if we won't use cacert.pem

What happens if I use this `curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);`
and don't use `curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, 1);
        curl_setopt($ch, CURLOPT_SSL_VERIFYHOST, 2);`
Thanks.

**Comment by overint** [comment]
> I want to know if 
> $this->use_local_certs = false;
> I mean what happens if we won't use cacert.pem

Depending on the environment, you may or may not have libcurl installed on the system (i.e. many windows servers and some linux servers). As the PHP Curl extension looks for `the system path where libcurl's cacert bundle is assumed to be stored` requests will fail if this file is missing. By including our own certificate bundle we can ensure this package works across all systems.

> What happens if I use this curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);
> and don't use curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, 1); curl_setopt($ch, CURLOPT_SSL_VERIFYHOST, 2);

These options would disable cert validation, meaning anyone could MITM connections between you and paypal. I would not recommend running queries this way unless you are debugging.

**Comment by quocbao1087** [comment]
What is difference between:
`$uri = 'https://'.$this->getPaypalHost().'/cgi-bin/webscr';`
`curl_setopt($ch, CURLOPT_URL, $uri);`
`curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);`
And
`$uri = 'http://'.$this->getPaypalHost().'/cgi-bin/webscr';`
`curl_setopt($ch, CURLOPT_URL, $uri);`
`curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);`

**Comment by quocbao1087** [comment]
About this change, https://devblog.paypal.com/paypal-ssl-certificate-changes/
If I use 
`$uri = 'https://'.$this->getPaypalHost().'/cgi-bin/webscr';`
`curl_setopt($ch, CURLOPT_URL, $uri);`
`curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);`
don't use cacert.pem 
Https above, does it mean I am using SSL and it involves to Paypal SSL change, and I need to update VeriSign G5 Root Certificate on server?

With that codes, will IPN Integration work after 30 September?

**Comment by overint** [comment]
Re; first question, paypal will start requiring postbacks to be made with HTTPS (currently, HTTP will work).
You can view the infomation here:
https://www.paypal-knowledge.com/infocenter/index?page=content&widgetview=true&id=FAQ1916&viewlocale=en_US 

As I said before, using `CURLOPT_SSL_VERIFYPEER, false` is extremely insecure, and can be easily MITM'd.
The cert bundle included with this package already contains the VeriSign G5 Root Certificate so no changes will be needed, and it will work fine after sep 30.

**Comment by quocbao1087** [comment]
One last question.
In this [https://devblog.paypal.com/paypal-ssl-certificate-changes/](url)
`1. Save the VeriSign G5 Root Trust Anchor in your keystore.`
This is cacert.pem in your src/cert right?
`2. Upgrade your environment to support the SHA-256 signing algorithm.`
I am only a developer. This can only do by host provider/system administrator right?
We can check our website is current support SHA-256 signing algorithm by this site right?
[https://shaaaaaaaaaaaaa.com/check/mediaacademy.sg](url)
If it shows my domain has a certificate chain signed with SHA-2.  It means this point 2 is OK right?

One other thing, I see this [https://www.symantec.com/page.jsp?id=compare-ssl-certificates&tid=ssl-sem](url)
what is this, why we need to buy, this is for point 1 or points 2 above?

Thank you very much!!

**Comment by overint** [comment]
1) Yep.
2) You do not need to upgrade the certificate on your website. You just need to ensure any calls made to paypal are made with SHA-256. 
You are using SHA-256 anyway, since SHA-2 is simply short for SHA-256. You do not need to buy anything :)

**Comment by overint** [comment]
I just checked your site, it seems you are only running HTTP, not HTTPS. While this is not an issue, you should look into getting a secure site up 😄

**Comment by quocbao1087** [comment]
Hi Overint,

What does this means? 
`curl_setopt($ch, CURLOPT_SSLVERSION, 4);`
If I don't add in this line, may have any issues?

**Comment by overint** [comment]
That sets the connection to TLS 1.2, which is required.

**Comment by quocbao1087** [comment]
so that line is required? I need to add it into paypalIPN.php?
I don't see that line in your paypalIPN.php.

If I don't add it into paypalIPN.php? what happens? any issues?

**Comment by overint** [comment]
Good catch. While it's not explicitly required (since the connection will default to tls 1.2) I will add it now. 
Thanks
